# application.yml

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: catalogus123@gmail.com
    password: catalogus12#
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
    
    